# stage.yml

# Define the name and description for this workflow.
name: CICD for Nodejs Application with Docker to Sage
run-name: ${{ github.actor }} is running CICD for Nodejs Application with Docker to Stage

# Define the trigger conditions for this workflow.
on:
  push:
    branches:
        stage
  workflow_dispatch:   
    
# Define the jobs that will be executed as part of this workflow.
jobs:
    deploy-to-stage:
      # Define the "build" job, which runs on the latest version of Ubuntu.
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout
          uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - run: npm install
        - name: Run test,js
          run: node test.js
  
        - name: print environment
          run: | 
            echo "The current environment is ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
            
  
        - name: your action
          run: |
            echo "Now you can continue with your project!"
